- lib/mochify.js
If coverify runs before a transform such as [reactify](https://github.com/andreypopp/reactify), it interferes with the JSX transform resulting in failure to run the tests. Moving the converify transform later in the process fixes running test files written in JSX (via `mochify --cover --transform reactify`).
Unfortunately, this does not change the transform ordering for browserify transforms specified in `package.json`. Combining reactify (via `package.json`) and `--cover` will still fail.
> Add coverify transform after command-line transforms.

- README.md
- lib/args.js
- lib/help.txt
- lib/mochify.js
- test/args-test.js
Following on from issue #68. Added a `recursive` flag which changes the glob used to find test files to run through Browserify. Imitates Mocha's `recursive` option.
Tests follow on from existing args coverage. I added checks that Mochify accepts the recursive option and sets it correctly. Any suggestions for how to better test this option is doing its job?
> Add recursive flag to include tests in subdirectories

- lib/mochify.js
- test/api-test.js
- test/fixture/glob/ignore/excluded.js
- test/fixture/glob/ignore/included.js
- test/node-test.js
- test/phantom-test.js
I've structured my app specific code using [local npm modules](http://www.devworkflows.com/posts/using-local-npm-modules-in-npm-v2-0/). 
```
/
index.js
package.json
test/
index.js
lib/
my-local-module/
index.js
package.json
test/
index.js
node_modules/ #I want to ignore all test files in this directory
some-remote-module/
index.js
package.json
test/
index.js
```
I want to run all the test files in the local modules but not the test files in their dependencies. This PR passes through [glob options](https://www.npmjs.com/package/glob#options) to the `glob` module allowing me to ignore the test files I don't want to run.
```js
mochify('./assets/**/test/*.js', {glob: {ignore: './assets/**/node_modules/**/test/*.js'}});
```
---
In #83 you asked how a similar set of options could be specified …
> passthru glob options so I can ignore files

- README.md
- lib/args.js
- lib/help.txt
- lib/phantom.js
- package.json
- test/args-test.js
Pass the new ignore-ssl-errors options to Phantomic.
Ignore PR#98, bottom line was there was an issue of how I was testing where there is no output if a test is running long with a high timeout, no progress indicator was running that a test is running, just a blank console. The fix would be to add an indicator something is running.
> Add the option to ignore ssl errors

- README.md
- lib/phantom.js
- package.json
- scripts/postinstall.js
- the script first checks to see if there is a local installation of package `phantomjs`
- if not, then it checks the PATH
- if it's not there, it goes ahead and installs it locally
- the `lib/phantom.js` module will default to using the global `phantomjs`, then fallback to local if it cannot be found.  `opts.phantomjs` overrides any of this.
- updated `README.md`
- add `which@^1.1.1` dependency
I wasn't sure how to test if the `phantomjs` executable was found.  since your tests in `test/phantom.js` are more of the integration variety, I figured it's covered if they pass.  Since Travis has it installed globally, we won't get coverage on a local install.  A solution may be to zap `process.env.PATH` and run the `phantom` tests a second time.
> add postinstall script to use global phantomjs by default; closes #90

- lib/phantom.js
If there are any syntax errors of any build steps that fail before it makes it to Phantomjs, Mochify stdouts a bunch of unnecessary stack trace data related to the input stream missing. This makes it tedious to track down that it was an error before my tests actually ran and not an error in my tests.
> Only write to input if input stream is defined

- package.json
My unit tests are currently failing and the issue seems to point towards an issue with a recently released version of [mocaccino](https://github.com/mantoni/mocaccino.js), version 1.6.
This PR uses the tilde rather than the caret to pin the version to only take minor updates.
Hopefully once mocaccino is fixed this amendment can be reverted.
> Pin Mocaccino to version 1.5 due to breaking change

- lib/args.js
- lib/mochify.js
- test/api-test.js
- test/args-test.js
- test/fixture/paths/some-module.js
- test/fixture/paths/test/path-test.js
This is similar to pull requests https://github.com/mantoni/mochify.js/pull/124 and https://github.com/mantoni/mochify.js/pull/83, supporting only the browserify paths option.
> Pass '--path' option to browserify.

- README.md
- lib/args.js
- lib/help.txt
- lib/mochify.js
- test/args-test.js
- test/fixture/browser-field/node_modules/some-module/browser.js
- test/fixture/browser-field/node_modules/some-module/index.js
- test/fixture/browser-field/node_modules/some-module/package.json
- test/fixture/browser-field/test/browser-field.js
- test/node-test.js
This is follow-up of #136.
As specified in https://github.com/mantoni/mochify.js/pull/136#issuecomment-214792372, I created fixtures to test against the case where the browser field of test's dependency is involved in the test code. It's located in `test/fixture/browser-field`.
> Implement --browser-field option

- .eslintrc
- lib/consolify.js
- lib/mochify.js
- package.json
- test/api-test.js
- test/args-test.js
- test/fixture/sandbox.js
* Fail with a useful error if the user tries to use --bundle wihout --consolify
* Add test-coverage to check that both the consolify'd HTML and extracted bundle are written to disk
> Add Test Coverage for --bundle and --consolify args 

- test/phantom-test.js
- test/stack-test.js
Discovered this in the process of attempting to fix a "bug" in #137
> [test] fix tests for new tap version that was pulled

- README.md
- lib/args.js
- lib/help.txt
- lib/mochify.js
- test/args-test.js
- test/fixture/external/test/passes.js
- test/node-test.js
In some situation such as [running enzyme with Browserify](https://github.com/airbnb/enzyme/blob/master/docs/guides/browserify.md), passing `external` option to Browserify is essential. This patch is intended to fill up missing `--external` feature to Mochify.js. Thanks.
> Implement --external option

- .eslintrc
- lib/args.js
- package-lock.json
- package.json
- scripts/postinstall.js
- test/api-test.js
- test/args-test.js
- test/fixture/api.js
- test/fixture/fails-cover/test/cover.js
- test/fixture/run.js
- test/fixture/sandbox.js
- test/node-test.js
- test/phantom-test.js
- test/stack-test.js
- test/trace-test.js
The `space-after-keywords`, `space-before-keywords` and `space-return-throw-case` settings where replaced with `keyword-spacing`. Otherwise the config is left untouched.
New recommended settings required changes in the code regarding indentation and consistent returns.
> Update dependencies and use eslint v3

- lib/args.js
- lib/chromium.js
- test/args-test.js
See https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-fails-due-to-sandbox-issues
This passes  the mentioned flags above to chrome: `--no-sandbox --disable-setuid-sandbox`.
These are required to run Chrome as the root user. This fixes #162.
> Added a flag to allow chrome to run as root

- README.md
- lib/args.js
- lib/chromium.js
- test/args-test.js
- test/chromium-test.js
- test/fixture/port/test/port.js
When no port is given for the --https-server arg, pick a random free one.
When a port is specified but already in use, fail with a meaningful error message.
This would solve #165 and #164.
I'm unsure about a few things, so I'll also leave comments in the diff.
> Improve port handling for https server

- README.md
- lib/args.js
- lib/chromium.js
- test/args-test.js
- test/chromium-test.js
- test/fixture/port/test/port.js
When --url is given, the port to be used by the local https server can be derived in case the --https-server arg is empty.
This is part 2 of #164.
> Enable passing of url without additionally specifying port

- README.md
- lib/help.txt
Looks like this is not fully documented yet.
> Document async polling arg in readme and help text

- package-lock.json
```text
=== npm audit security report ===
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ https-proxy-agent                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ min-wd                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ min-wd > saucelabs > https-proxy-agent                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ …
```
> Dependency hygeine (npm audit)

- .travis.yml
- lib/chromium.js
- package-lock.json
- package.json
- test/args-test.js
- test/chromium-test.js
- test/fixture/console/test/console.js
- test/fixture/run.js
- test/node-test.js
Puppeteer >= 1.4.0 introduced changes that will change the
way messages are passed to `console` events. To filter out
non-test related messages, filter all non-log messages. Also
bump puppeteer to ^1.4.0 and start testing in Node 10.
So this is fixing #171 - looks like we got bitten by: https://github.com/GoogleChrome/puppeteer/pull/2400 which changes what kind of messages will trigger a `console` event.
> Filter out non-log messages when reading console

- README.md
- package-lock.json
- package.json
Allows mochify to take advantage of custom capabilities, which lets us specify browser options, set up BrowserStack integration, etc.
Would you like me to add some more helpful documentation to make people aware of the new features in min-wd? Do we need tests?
> Update min-wd to 2.11.0

- lib/mochify.js
- test/chromium-test.js
This is an attempt at fixing #177.
Tests and all seem to pass and it also fixes the issue in the example repo provided in the issue, then again I am slightly worried if it is even a good idea to potentially add browserify plugins asynchronously or if this needs some bigger refactoring in order to do everything synchronously always.
>  Ensure browserify plugins are always mounted in the same order

- lib/args.js
- lib/mochify.js
- test/args-test.js
When looking at #180 I noticed that the validation of the server port was done in the `args` module, when everything else would be validated in `mochify`. This simply moves things to the same location.
> Consolidate validation of options in one place

- lib/mochify.js
- lib/server.js
I looked into the `node` plugin issue from #178 which led nowhere and gave me a terrible headache :pill:. I feel browserify does not really expect plugins and transforms to be "maybe" added asynchronously, at least I wasn't able to find any logic in what was called in which order if plugins were added like this.
Instead I moved all the main action on `b` back into the synchronous `mochify` call, so it's 100% foolproof that the calls will be executed in the supposed order.
The server will still be created asynchronously, which means we rely on puppeteer to wait for it to be ready, but that's what's happening at the moment as well and is the price for not deferring `bundle()` until setup has happened.
I feel this is quite a bit saner than #178, but maybe there's other input as well.
> Do not add plugins on browserify object asynchronously to ensure predictable order

- README.md
I think this is what caused the confusion about the build status in #180 
`master` is all green at the moment: https://travis-ci.org/mantoni/mochify.js/branches
> Display build status from master in README

- package-lock.json
- package.json
This means that cached-path-relative will be upgraded to 1.0.2, which
fixes a security warning:
See: https://nvd.nist.gov/vuln/detail/CVE-2018-16472
> Upgrade browserify and watchify

- package-lock.json
- package.json
Mocaccino used to load Mocha 4 still, causing two Mocha versions to be installed.
This is going to be a patch for v6.
> Upgrade Mocaccino to v4

- lib/server.js
- package.json
This adds `mime` as a dependency to lookup the content-type based on the file extension. This package was chosen because it's already used by Puppeteer, hence it's not adding any weight.
Fixes the failing webworker test in https://github.com/sinonjs/sinon/pull/1950 🎉
> Serve files with content-type headers

- lib/chromium.js
When looking at the issue from #189 I noticed that errors when calling browser.newPage() will never be handled (thus causing timeouts). This is the full stack trace for the `UnhandledPromiseRejectionWarning`:
```
(node:173) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.enable): Target closed.
at Promise (/home/circleci/repo/node_modules/puppeteer/lib/Connection.js:186:56)
at new Promise (<anonymous>)
at CDPSession.send (/home/circleci/repo/node_modules/puppeteer/lib/Connection.js:185:12)
at Function.create (/home/circleci/repo/node_modules/puppeteer/lib/Page.js:44:18)
at _pagePromise._sessionFactory.then.client (/home/circleci/repo/node_modules/puppeteer/lib/Target.js:43:32)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7)
-- ASYNC --
at …
```
> Handle promise rejection when calling browser.newPage()

- lib/args.js
- lib/chromium.js
- test/args-test.js
- test/chromium-test.js
To make debugging easier, support passing this option on to puppeteer.
With regards to the test, I am not at all sure it's what you want. I just wasn't able to figure out how to do a regex match that would produce meaningful assertion errors using the standard `assert` module, so I decided just to test on a subset of the string.
closes #199 
Background: sinonjs/sinon#1999
> Enable support for passing --dumpio to Puppeteer

- README.md
- lib/args.js
- lib/chromium.js
- test/args-test.js
- test/chromium-test.js
- test/fixture/web-security/test.html
- test/fixture/web-security/test/web-security.js
There used to be a flag in old versions called `--web-security` (added in #71) which allowed disabling the same-origin policy in Phantom. Now that we use Puppeteer/Chromium, that flag was removed. This PR adds it back in with the exact same semantics it used to have, but it now passes through to Chromium.
Happy to adjust as needed. Thanks!
> [feat] Bring back --web-security flag

- lib/args.js
- lib/chromium.js
- test/args-test.js
- test/chromium-test.js
This works around a puppeteer issue when running scripts within a web worker. See https://github.com/GoogleChrome/puppeteer/issues/4208 for details.
> Introduce `--no-request-interception`

- lib/args.js
- lib/mochify.js
- package-lock.json
- package.json
- test/args-test.js
- test/chromium-test.js
- test/fixture/async/test/async.js
- test/fixture/detect-globals/test/global.js
By default, browserify detects the use of global like `process` and `global`. This is sometimes undesireable and recently caused issues with upgrading browserify in the Sinon projects (see https://github.com/sinonjs/commons/pull/37, https://github.com/sinonjs/sinon/pull/2119 and most importantly the analysis from @fatso83 in https://github.com/sinonjs/sinon/issues/2085).
Allowing to turn off this browserify behavior brought a chain of other issues to the light:
- The `brout` project (used internally) assumed that `process` is shimed. This has been addressed in `v1.3.0` (see https://github.com/mantoni/brout.js/commit/9fc88568629256cf47f03e8744124f50e4651a64).
- The `mocaccino` project (also used internally) assumed that `process.nextTick` is shimed. This has been addressed in `v4.1.2` (see …
> Add support for the browserify `--no-detect-globals` option

- README.md
- v15 is not yet supported (see https://github.com/istanbuljs/nyc/commit/cfd3da05156b98952f03f7be2dd3d23ba328073f)
- The babel plugin should run globally for some special cases to work
> Improve docs for nyc coverage

- .travis.yml
- lib/args.js
- lib/mochify.js
- package-lock.json
- package.json
And fix no-prototype-builtins errors
See: https://eslint.org/docs/rules/no-prototype-builtins
In another project I am trying to see if I can upgrade away from old `minimist` versions, to not have any security warnings.
Specifically https://www.npmjs.com/advisories/1179 against `minimist`.
The old version of `eslint` would cause an affected version of `minimist` to be installed.
Upgrading `eslint` to latest is safe, and takes care of one of the many versions of `minimist` installed, making my task a bit easier.
> Upgrade ESLint to latest

- README.md
- lib/chromium.js
From what I can tell, the only thing that breaks with nyc v15 is that it removes `NYC_ROOT_ID` (https://github.com/istanbuljs/nyc/blob/master/CHANGELOG.md#-breaking-changes) which is depended on by mochify.  I'm not sure how the ID is used, but it seems like any ID will work.  Therefore, for nyc>=15, I'm generating a random `NYC_ROOT_ID`.
> Support nyc v15

- package-lock.json
Also fixes some `npm audit` issues:
```
ini  <1.3.6
Prototype Pollution - https://npmjs.com/advisories/1589
fix available via `npm audit fix`
node_modules/fsevents/node_modules/ini
lodash  <4.17.21
Severity: high
Command Injection - https://npmjs.com/advisories/1673
fix available via `npm audit fix`
node_modules/lodash
```
> Npm update

- .travis.yml
- lib/chromium.js
- package-lock.json
- package.json
- test/api-test.js
- test/chromium-test.js
- test/node-test.js
Closes #213 
Most of the changes in this PR are related to change in TAP output in Mocha 8 discussed here: https://github.com/mantoni/mocaccino.js/pull/35#discussion_r633250254
---
The other issue we run into here is that the rollupified Mocha 8 browser bundle now prints a whole lot of deprecation warnings like:
```
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead
```
When I inspect a bundle in my browser the warning points here: https://github.com/mochajs/mocha/blob/34643e4c0821aeb8d6977c1942bc106c9363789a/browser-entry.js#L219 (or rather there plus some Rollup code around it).
For now I'm not entirely sure we could fix this in any other way than just swallowing these warnings?
> Upgrade to Mocaccino 5, use Mocha 8 and Puppeteer 9

- .github/workflows/test.yml
- .travis.yml
- README.md
The __org__ version of Travis seems to be shutting down on the 15th of June which isn't that far into the future anymore.
It would be possible to migrate the setup to the __com__ version (https://docs.travis-ci.com/user/migrate/open-source-repository-migration), but tbh that feels like a dead end. Instead, Mochify can use GitHub actions I guess.
> Migrate CI to GitHub actions

- package-lock.json
A simple `npm install` on top of the current master commit (3179da8).  I believe the changes in this PR were lost in some previous PR, perhaps because of past rebase/merge conflict resolution.
> Clean up package-lock.json

- package-lock.json
- package.json
`watchify` v3 has indirect security vulnerabilities.  `watchify` v4 resolves those vulnerabilities and has minimal incompatibilities.
[Watchify changelog](https://github.com/browserify/watchify/blob/master/CHANGELOG.md)
~~Also updates `puppeteer` to fix builds with node v16.  [Puppeteer changelog](https://github.com/puppeteer/puppeteer/blob/main/CHANGELOG.md)~~
> Update watchify package to v4.0.0

- package-lock.json
- package.json
This PR updates puppeteer from `^9.1.1` to `^10.0.0`.  This was done on top of #227 and split from #226.  
This PR was generated by 
1.  checking out master
2. `npm install` (getting to #227)
3. Updating package.json with the new puppeteer version
4. `npm install`
> Update puppeteer dependency

- driver-puppeteer/index.js
- mochify/lib/run.js
It seems that the puppeteer driver right now does not handle uncaught exceptions that occur before mocha is set up, so if your test suite is borked, this will right now result in sth like this:
```
➜  mochify.js git:(rewrite) ✗ npm t                                                                                                                                                                        
> mochify@8.1.0 test                                                                                                                                                                                       
> cli/index.js --bundle 'browserify --debug' ./test.js …
```
> Handle uncaught exceptions in puppeteer driver

- mochify/lib/poll-events.js
When debugging why the `jsdom` driver that I am working on was never running any tests I found out it's because of the following:
- in this setup `mochify` and `jsdom` run on the same thread
- the infinite loop that currently polls for events from the mochify reporter is blocking
- jsdom never gets around to execute any code because it's being blocked by the mentioned for loop
This is not a problem for headless browsers et al as they run on a different thread, yet I would assume allowing drivers to use the same thread as mochify can be helpful.
---
The [jsdom driver](https://github.com/mantoni/mochify.js/tree/jsdom-driver) works now including this change, but there's a lot of clean up to do still, so I thought this should go into a dedicated PR.
> Use non-blocking loop to poll for events

- driver-playwright/index.html
- driver-playwright/index.js
- driver-playwright/package.json
- package-lock.json
- package.json
This is so eerily similar to `puppeteer` as of now, I wonder if it should share some code or if we're ok with the duplication.
Dunno about your plans, but having seen how easy this is, I would assume it makes more sense to wait with merging this while you still figure out the API and things like the testing story.
This currently works fine (running very basic stuff) with all 3 engines.
> Add playwright driver

- driver-jsdom/index.html
- driver-jsdom/index.js
- driver-jsdom/package.json
- package-lock.json
- package.json
This adds a driver backed by `jsdom` which might be nice for environments that cannot run headless browsers or similar.
This seems to mostly work, apart from one issue where I'll comment inline.
> Add jsdom driver

- cli/index.js
- mochify/index.js
- mochify/lib/server.js
Simply to have fewer options, I thought we could do just with `--serve $PATH` and remove `--server`.
`--server` is the same as `--serve .`
> Remove --server option in favor of --serve

- cli/index.js
- mochify/index.js
- test.js
I was thinking how we could specify driver options and pass them down. In this example, I prefixed the `engine` option (used by the playwright driver) with `--driver-`.
I can think of these naming conventions:
- `--driver-${option}`
- `--${driver}-${option}`
- `--driver-${driver}-${option}`
Or we re-introduce the [subarg](https://www.npmjs.com/package/subarg) module and allow `--driver-options [ --engine webkit ]`.
What do you think?
> Add driver options

- .github/workflows/test.yml
- cli/package.json
- cli/test/config.integration.js
- cli/test/fixture/custom.config.yaml
- cli/test/fixture/fails.js
- cli/test/fixture/mochify.config.js
- cli/test/fixture/passes.js
- cli/test/jsdom.integration.js
- cli/test/playwright.integration.js
- cli/test/puppeteer.integration.js
- mochify/lib/inject-script.test.js
- mochify/lib/load-config.test.js
- mochify/package.json
- mochify/test/bundle.integration.js
- mochify/test/files.integration.js
- mochify/test/fixture/passes.js
- package-lock.json
- package.json
- test/hooks.js
This adds a few unit tests for the `mochify` module and some integration tests for the `mochify` and `cli` modules and runs them with GitHub actions.
Ref #229
> Add initial unit and integration tests for CLI and mochify

- cli/index.js
- cli/package.json
- driver-playwright/package.json
- driver-puppeteer/package.json
- mochify/index.js
- mochify/lib/resolve-spec.js
- mochify/lib/resolve-spec.test.js
- mochify/package.json
- mochify/test/bundle.integration.js
- mochify/test/spec.integration.js
- package-lock.json
- The cli was missing the bin config.
- The playwright and puppeteer drivers where missing `index.html` in the `files` array.
- It wasn't possible to declare files to include in a config file. Mocha allows to define `spec`, which is what mochify supports now as well.
> Allow to define "spec" in config and fix package.json

- cli/test/fixture/client-leak.js
- cli/test/jsdom.integration.js
- cli/test/playwright.integration.js
- cli/test/puppeteer.integration.js
- mochify/client.js
- mochify/lib/inject-script.js
- mochify/lib/inject-script.test.js
- mochify/lib/poll-events.js
Converted the `client.js` to es5 to support IE.
Worked around an issue in the mozilla geckodriver: mozilla/geckodriver#1798
> Rewrite: Fix webdriver for IE and Firefox

- driver-puppeteer/README.md
- driver-puppeteer/index.js
- driver-puppeteer/package.json
Resolves #245 
I opted for allowing users to pass through all of the available `launchOptions` to puppeteer while still applying some sane defaults. I have to admit I found writing the docs for this kind of hard, so maybe that's a sign this could be done better?
> Allow passing through launch options to driver-puppeteer

- driver-puppeteer/index.js
This is a fixup for #252
It seems that when passing multiple values through the CLI like:
```
mochify --driver-options.args='--allow-chrome-as-root' --driver-options.args='--no-sandbox'
```
`yargs` will pass  `['-allow-chrome-as-root',  '--no-sandbox']` when passing a single value like
```
mochify --driver-options.args='--allow-chrome-as-root'
```
will yield the plain string `'--allow-chrome-as-root'`
> Cater for cases when puppeteer driver args is a string only

- .github/workflows/test.yml
- mochify/index.js
- mochify/lib/resolve-bundle.js
- mochify/lib/server.js
From what I understand we still support Node 12 where importing `fs/promises` fails and needs to be `require('fs').promises` instead. See: https://nodejs.org/api/fs.html#fs_promises_api
Alternatively we could of course also drop support for 12 for the rewrite, but then again I really hope we can get this shipped before its EOL (which is end of April 2022).
> Import fs/promises in a way that is compatible with Node 12 still

- driver-jsdom/index.js
- mochify/index.js
This is an alternative implementation of #259 which retains parallel execution of the driver and the bundler. These are the two sub processes that may take a while, so I would prefer to not run them sequentially.
One of the integration tests highlighted that the `driver-jsdom` doesn't return a promise, which this fixes as well.
> Shutdown on errors

- cli/index.js
- mochify/index.js
This picks up https://github.com/mantoni/mochify.js/pull/259#issuecomment-916875460
Technically this is a breaking change, so maybe you want to wait with merging this before we do a `0.3.0`?
> Return exit code from main API method instead of setting it

- cli/test/config.integration.js
- cli/test/fixture/custom.config.yaml
- cli/test/fixture/mochify.config.js
- mochify/index.js
This PR addresses two issues:
I noticed I could run tests when not specifying any `driver`. I'm not sure if we want this as installing `@mochify/cli` or `@mochfiy/mochify` does not provide any driver implementation themselves and consumers would see a message about how a module could not be found when trying to run it, probably thinking this is a bug. Instead we can provide a clear error message about it.
The logic I implemented in #253 has one really awful flaw: Assuming you try passing `jsdom` as the driver without having installed it (whre it = `@mochify/driver-jsdom`), the logic would fall back to requiring `jsdom` which might be installed or resolvable because it's used by something else and then Mochify would try to use the main export of the `jsdom` module as a driver. I don't even …
> Do not assume availability of default driver, prevent accidental fall back to wrong modules

- cli/test/playwright.integration.js
Picking up: https://github.com/mantoni/mochify.js/pull/241/files/ca46f4857c81b0473a406ef5129b0d69e675bad5#r680548654
As this worked on first attempt (i.e. as documented) I'm not sure why it failed back then? Maybe it's because of 51db9e2aabe90a09a3a6ca3aaeb16a011bdcd732 (I did notice that Firefox was significantly slower than Chromium when adding the initial version of the driver so it would make sense)?
> Run playwright integration tests in Firefox

- cli/README.md
- cli/index.js
This is a first pass at adding some content and structure to the output of `mochify --help`. Right now, this is relatively wordy (maybe a little too wordy) as it's the only documentation around, I think it should be possible to reduce the amount of inline docs over time (moving it to `@mochify/mochify`).
> Rewrite: Add help and example content for CLI module

- cli/index.js
It seems #267 introduced a subtle breakage: it seems yargs now somehow parses `spec` by itself, rendering the logic around `opts._` unneccessary. This would be fine all by itself (we could remove https://github.com/mantoni/mochify.js/blob/b407d82bda319251e7dcda039bbbd4a273d6224b/cli/index.js#L96-L98) until #268 enters the stage: when handling positional arguments yargs will just eat `-` without any further notice: https://github.com/yargs/yargs/issues/1312
Why did I introduce the nested command in #267 the first place? It seems that if you pass a second argument to `.usage()` yargs will somehow not display `example`, `epilogue` and such unless you start attaching it to the child instance, which means this PR needs to drop the command description again. I don't know if this is a bug in …
> Unnest yargs definition to restore argv._

- cli/README.md
- cli/index.js
- cli/test/jsdom.integration.js
- cli/test/playwright.integration.js
- cli/test/puppeteer.integration.js
- mochify/index.js
- mochify/lib/load-config.js
- mochify/lib/load-config.test.js
- mochify/lib/resolve-bundle.js
- mochify/lib/resolve-spec.js
- mochify/lib/resolve-spec.test.js
- mochify/lib/validate-config.js
- mochify/lib/validate-config.test.js
> Allow reading bundle from stdin

- mochify/index.js
- mochify/lib/mochify-driver.js
- mochify/lib/mochify-driver.test.js
Consumers of the API module might want to pass in a custom (?) driver module instead of having to rely on Mochify to do the resolution:
```js
mochify({
driver: require('./my-driver-thing'),
...other
})
```
---
While this might look simple in the above snippet, there is one thing I am not sure about: does this mean that you're using a `.js` config file, you could require the driver in there and pass it down? In case yes, do we want that or should config stay rather dumb?
> Allow driver option to be a module on API level

- driver-jsdom/index.js
- driver-playwright/index.js
- driver-puppeteer/index.js
- driver-webdriver/index.js
- mochify/client.js
- mochify/lib/poll-events.js
- mochify/lib/setup-client.js
- mochify/lib/setup-client.test.js
Picks up: https://github.com/mantoni/mochify.js/pull/232/files/5aecae9f8be4f783f27877808fe4496481cc71dd#r667336402
Just prepending `return` seems to limit ourselves to immediately return the first expression in the given script, but wrapping the script in an IIFE seems to work as expected.
This should probably merged after #274 so it can be rebased against `rewrite` before and pass the tests (it does pass locally for me).
> Wrap webdriver script content in IIFE, removing need for evaluateReturn

- package-lock.json
- package.json
Allows users of Mochify to get rid of a warning about `nanoid` https://github.com/mantoni/mocaccino.js/security/advisories
Also see:
- https://github.com/mantoni/mocaccino.js/pull/40
- https://github.com/mochajs/mocha/pull/4818
> Update mocaccino to 6.1.0 /mocha to 9.2.0

- package-lock.json
- package.json
This updates to the latest version of puppeteer to get rid of annoying security vulnerability warnings.  There are multiple major version changes but none of the breaking changes seem to affect mochify.  
See [puppeteer's changelogs](https://github.com/puppeteer/puppeteer/blob/main/CHANGELOG.md).
> Update puppeteer to v13
