mantoni/mochify.js

lib/args.js
lib/help.txt
lib/mochify.js
test/node-test.js

Simple extension to support browserify options via subargs.

Added support for browserify options via subargs

---

README.md
lib/args.js
lib/help.txt
lib/phantom.js
test/args-test.js

As discussed in https://github.com/mantoni/mochify.js/issues/69.
Please let me know if you want me to tweak it somehow!

Add `--web-security` option to toggle PhantomJS web security

---

lib/mochify.js

pass colors through to mocaccino

---

CHANGES.md
README.md
lib/mochify.js
package.json
test/api-test.js

Mochify support for reporterOptions.
#143

Support reporterOptions

---

lib/mochify.js
test/fixture/require/test/passes.js
test/node-test.js
test/phantom-test.js

I was trying to use the require flag, and it was not working.  I believe this PR is the intended behavior, right?

Fix behavior of --require flag

---

README.md
package-lock.json
package.json

Updates the Growl dependency that had a vulnerability
See
- https://snyk.io/vuln/npm:growl:20160721
- https://www.bithound.io/github/sinonjs/lolex/master/dependencies/npm/mochify#security-advisories

Update to Mocha 4

---

lib/args.js
test/args-test.js

Properly cast viewport parameters to ints

---

package-lock.json
package.json

Update the core dependencies to more recent versions.
New `changes --commits --footer` features generate a more expressive changelog.

Mocha 5.2, Puppeteer 1.10 and Studio Changes 1.7

---

README.md
lib/chromium.js

~~_Work in progress! Do not merge!_~~
This ~~is an attempt to integrate~~ integrates mochify with `nyc`. It works ~~for small projects~~, but requires quite some complicated setup.
It might be a better option to write a custom transform in this project, that uses the recent implementation of the istanbul instrumenter directly.
Ref https://github.com/sinonjs/sinon/issues/1948

nyc support

---

lib/chromium.js
test/chromium-test.js
test/fixture/fails-async/test/fails-async.js
test/node-test.js

This is a possible fix for #191

Do not exit on puppeteer pageerror event

---

lib/chromium.js
package-lock.json
package.json

This is an attempt to get more information than `[object Object]` in the failing build here: https://github.com/sinonjs/sinon/pull/1995

Inspect page error objects

---

README.md
lib/chromium.js
lib/help.txt
test/chromium-test.js

See discussion on https://github.com/mantoni/mochify.js/pull/200.

Dumpio part 2

---

package-lock.json
package.json
test/chromium-test.js

This PR seems to finally fix the flaky builds. I ran the tests several times locally and the Travis build on the branch is also green on the first attempt 🎉

Puppeteer 1.19.0

---

README.md
lib/chromium.js
package-lock.json
package.json

This upgrades puppeteer to latest (v8.0.0) and adds a workaround for https://github.com/puppeteer/puppeteer/issues/6957.

Workaround for Apple Silicon

---

driver-jsdom/index.html
driver-jsdom/index.js

- Inline html page
- Pass url through and default to http://localhost
- Pretend to be visual so that requestAnimationFrame works
- Turn of strict SSL checks

Improve jsdom setup

---

cli/index.js
driver-webdriver/README.md
driver-webdriver/index.js
mochify/index.js
mochify/lib/load-config.js
mochify/package.json
package-lock.json

This change allows to configure mochify in `package.json` and various config file formats.
Users can specify a file with the `--config` option. If a config file is specified and a default configuration is also present, the configs are merged.
Command line options override the config file options. A custom config file overrides settings from the default config.

Load config with cosmiconfig

---

cli/LICENSE
cli/package.json
driver-jsdom/LICENSE
driver-jsdom/package.json
driver-playwright/LICENSE
driver-playwright/package.json
driver-puppeteer/LICENSE
driver-puppeteer/package.json
driver-webdriver/LICENSE
driver-webdriver/package.json
mochify/LICENSE
mochify/package.json
package-lock.json
package.json

In preparation for a `0.1.0` release of the rewrite this change
- configures the version lifecycle scripts
- adds meta data to `package.json` files
- adds LICENSE files to the npm modules

Release setup

---

mochify/index.js

Allow external drivers

---

mochify/lib/load-config.js
mochify/lib/load-config.test.js
mochify/package.json
package-lock.json

Fixes #255 
Introducing the `deepmerge` dependency is kind of the nuclear option here, but I found myself hunting way too many edge cases when trying to implement this myself. If you prefer to solve this without a dependency let me know and I can see what I can get figured out.

Deep merge config objects

---

driver-jsdom/README.md
driver-jsdom/index.js
driver-jsdom/package.json
driver-puppeteer/README.md

Allow passing down options to JSDOM

---

.github/workflows/test.yml
cli/test/webdriver.integration.js

Closes #246 
I rarely run Selenium locally, so I am not sure what the most common setups are here. I tested this using the same Docker image as in the CI setup and it worked fine.
Is it ok to skip the tests if not in CI and there is no server running?

Run integration tests for driver-webdriver against selenium server

---

cli/test/config.integration.js
mochify/lib/load-config.js
mochify/lib/load-config.test.js
mochify/package.json
package-lock.json
package.json

Switching to `lilconfig` for fewer dependencies. Removes yaml config support.

Replace cosmiconfig with lilconfig
